Include programname in default JSON template
rsyslog/rsyslog pull request #4592
Opened 2021-05-15 02:33 UTC by artbristol

The default JSON template does not include the programname.
This makes it difficult to know which program wrote which log entry.

2021-05-15 02:46 UTC, davidelang commented
the programname should be part of the syslogtag (or in the rfc5424 headers), is 
that not the case for your logs?

could you show us a sample log message?

David Lang

On Fri, 14 May 2021, Art O Cathain wrote:

> Date: Fri, 14 May 2021 19:33:33 -0700
> From: Art O Cathain ***@***.***>
> Reply-To: rsyslog/rsyslog
>     ***@***.***>
> To: rsyslog/rsyslog ***@***.***>
> Cc: Subscribed ***@***.***>
> Subject: [rsyslog/rsyslog] Include programname in default JSON template
>     (#4592)
> 
> The default JSON template does not include the programname.
> This makes it difficult to know which program wrote which log entry.
> You can view, comment on, or merge this pull request online at:
>
>  https://github.com/rsyslog/rsyslog/pull/4592
>
> -- Commit Summary --
>
>  * split lines for readability
>  * Add programmname
>
> -- File Changes --
>
>    M runtime/rsconf.c (11)
>
> -- Patch Links --
>
> https://github.com/rsyslog/rsyslog/pull/4592.patch
> https://github.com/rsyslog/rsyslog/pull/4592.diff
>
>

2021-05-15 03:14 UTC, artbristol commented
I'm using omelasticsearch. With the default configuration (no template configured so it uses the default JSON one) a log message looks like this in Elasticsearch

```
{
  "_index": "system",
  "_type": "events",
  "_id": "jdr_bXkBNi6M-_cW0TEk",
  "_version": 1,
  "_score": null,
  "fields": {
    "facility.keyword": [
      "auth"
    ],
    "timegenerated": [
      "2021-05-15T03:09:12.342Z"
    ],
    "message.keyword": [
      " Received disconnect from 103.136.42.230 port 51208:11: Bye Bye [preauth]"
    ],
    "fromhost.keyword": [
      "storage"
    ],
    "fromhost": [
      "storage"
    ],
    "message": [
      " Received disconnect from 103.136.42.230 port 51208:11: Bye Bye [preauth]"
    ],
    "priority": [
      "info"
    ],
    "timereported": [
      "2021-05-15T03:09:12.342Z"
    ],
    "facility": [
      "auth"
    ],
    "priority.keyword": [
      "info"
    ]
  },
  "highlight": {
    "fromhost": [
      "@kibana-highlighted-field@storage@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1621048152342
  ]
}
```
This message is from `sshd` but you can't tell that.

I used a custom template and added the programname to get messages that look like this in Elasticsearch

```
{
  "_index": "system",
  "_type": "events",
  "_id": "39rzbXkBNi6M-_cWSSLk",
  "_version": 1,
  "_score": null,
  "fields": {
    "facility.keyword": [
      "auth"
    ],
    "timegenerated": [
      "2021-05-15T02:55:31.298Z"
    ],
    "programname.keyword": [
      "sshd"
    ],
    "message.keyword": [
      " Received disconnect from 178.128.125.217 port 54098:11: Bye Bye [preauth]"
    ],
    "programname": [
      "sshd"
    ],
    "fromhost.keyword": [
      "storage"
    ],
    "fromhost": [
      "storage"
    ],
    "message": [
      " Received disconnect from 178.128.125.217 port 54098:11: Bye Bye [preauth]"
    ],
    "priority": [
      "info"
    ],
    "timereported": [
      "2021-05-15T02:55:31.298Z"
    ],
    "facility": [
      "auth"
    ],
    "priority.keyword": [
      "info"
    ]
  },
  "highlight": {
    "fromhost": [
      "@kibana-highlighted-field@storage@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1621047331298
  ]
}
```

2021-05-15 08:38 UTC, davidelang commented
all you would need to do with the default template is add the line

set $!programname.keyword = $programname;

to set the variable in the $! namespace, and then it will get picked up by the 
default template.

David Lang

On Fri, 14 May 2021, Art O Cathain wrote:

> Date: Fri, 14 May 2021 20:14:18 -0700
> From: Art O Cathain ***@***.***>
> Reply-To: rsyslog/rsyslog
>     ***@***.***>
> To: rsyslog/rsyslog ***@***.***>
> Cc: David Lang ***@***.***>, Comment ***@***.***>
> Subject: Re: [rsyslog/rsyslog] Include programname in default JSON template
>     (#4592)
> 
> I'm using omelasticsearch. With the default configuration (no template configured so it uses the default JSON one) a log message looks like this in Elasticsearch
>
> ```
> {
>  "_index": "system",
>  "_type": "events",
>  "_id": "jdr_bXkBNi6M-_cW0TEk",
>  "_version": 1,
>  "_score": null,
>  "fields": {
>    "facility.keyword": [
>      "auth"
>    ],
>    "timegenerated": [
>      "2021-05-15T03:09:12.342Z"
>    ],
>    "message.keyword": [
>      " Received disconnect from 103.136.42.230 port 51208:11: Bye Bye [preauth]"
>    ],
>    "fromhost.keyword": [
>      "storage"
>    ],
>    "fromhost": [
>      "storage"
>    ],
>    "message": [
>      " Received disconnect from 103.136.42.230 port 51208:11: Bye Bye [preauth]"
>    ],
>    "priority": [
>      "info"
>    ],
>    "timereported": [
>      "2021-05-15T03:09:12.342Z"
>    ],
>    "facility": [
>      "auth"
>    ],
>    "priority.keyword": [
>      "info"
>    ]
>  },
>  "highlight": {
>    "fromhost": [
>      ***@***.***@storage@/kibana-highlighted-field@"
>    ]
>  },
>  "sort": [
>    1621048152342
>  ]
> }
> ```
> This message is from `sshd` but you can't tell that.
>
> I used a custom template and added the programname to get messages that look like this in Elasticsearch
>
> ```
> {
>  "_index": "system",
>  "_type": "events",
>  "_id": "39rzbXkBNi6M-_cWSSLk",
>  "_version": 1,
>  "_score": null,
>  "fields": {
>    "facility.keyword": [
>      "auth"
>    ],
>    "timegenerated": [
>      "2021-05-15T02:55:31.298Z"
>    ],
>    "programname.keyword": [
>      "sshd"
>    ],
>    "message.keyword": [
>      " Received disconnect from 178.128.125.217 port 54098:11: Bye Bye [preauth]"
>    ],
>    "programname": [
>      "sshd"
>    ],
>    "fromhost.keyword": [
>      "storage"
>    ],
>    "fromhost": [
>      "storage"
>    ],
>    "message": [
>      " Received disconnect from 178.128.125.217 port 54098:11: Bye Bye [preauth]"
>    ],
>    "priority": [
>      "info"
>    ],
>    "timereported": [
>      "2021-05-15T02:55:31.298Z"
>    ],
>    "facility": [
>      "auth"
>    ],
>    "priority.keyword": [
>      "info"
>    ]
>  },
>  "highlight": {
>    "fromhost": [
>      ***@***.***@storage@/kibana-highlighted-field@"
>    ]
>  },
>  "sort": [
>    1621047331298
>  ]
> }
> ```
>
>
>

2021-05-17 04:35 UTC, artbristol commented
> all you would need to do with the default template is add the line set $!programname.keyword = $programname; to set the variable in the $! namespace, and then it will get picked up by the default template. David Lang

Thanks for the reply. (I've already solved the issue as I mentioned)

The reason I opened this PR is to make it easier for people new to rsyslog to be able to hook it up to Elasticsearch. Adding the line you mention - do you think this should be documented somewhere? (Or is it there already and I missed it?)

2021-05-17 06:40 UTC, davidelang commented
set is well documented, the details of the line will depend on what you want it 
to look like (programename.keyword is what you used in your example, so that's 
what I used in mine)

There are other properties that are not in the default $! set that someone may 
want added (hostname, timestamp, fromhost-ip, actually just about any of them 
_could_ be wanted), so there isn't any documentations specifying any of them in 
particular.

David Lang

  On Sun, 16 May 2021, Art O Cathain wrote:

> Date: Sun, 16 May 2021 21:35:34 -0700
> From: Art O Cathain ***@***.***>
> Reply-To: rsyslog/rsyslog
>     ***@***.***>
> To: rsyslog/rsyslog ***@***.***>
> Cc: David Lang ***@***.***>, Comment ***@***.***>
> Subject: Re: [rsyslog/rsyslog] Include programname in default JSON template
>     (#4592)
> 
>> all you would need to do with the default template is add the line set $!programname.keyword = $programname; to set the variable in the $! namespace, and then it will get picked up by the default template. David Lang
>
> Thanks for the reply. (I've already solved the issue as I mentioned)
>
> The reason I opened this PR is to make it easier for people new to rsyslog to be able to hook it up to Elasticsearch. Adding the line you mention - do you think this should be documented somewhere? (Or is it there already and I missed it?)
>
>

2021-05-17 11:13 UTC, artbristol commented
I appreciate your taking the time to reply and sharing your expertise. Could you step back and look at this issue as a newcomer to rsyslog might?

Someone following the documentation here https://www.rsyslog.com/doc/v8-stable/configuration/modules/omelasticsearch.html, in particular the Example 1 section, will end up with logs that do not include the programname. In my opinion, these logs are much less useful without it, to the point of being unusable.

Compare the file log output that Rsyslog, also in the default configuration, writes to /var/log/auth.log for the same event:

```
2021-04-28T22:33:57.069302+01:00 tilca sshd[9432] Received disconnect from 103.136.42.230 port 60906:11: Bye Bye [preauth]
```

This includes the timestamp, hostname, programname, and message.

I think sane defaults matter a lot and either the documentation I link to should be updated (I'm happy to make the change) or preferably the default JSON logging output should include the programname.

2022-02-07 08:18 UTC, rgerhards requested changes
breaks backward-compatiblility (see main discussion thread).

2022-02-07 19:08 UTC, artbristol commented
> The problem with this PR is that it breaks backwards-compatibility. We would need to define a new canned template for this and update the doc. @artbristol still any interest in doing that? Else I would consider taking your PR as basis and doing it myself.

Hi, yes thanks for the reply. I'm happy to define a new template and update the docs.

2022-02-07 20:50 UTC, davidelang commented
On Mon, 7 Feb 2022, Art O Cathain wrote:

>> The problem with this PR is that it breaks backwards-compatibility. We would need to define a new canned template for this and update the doc. @artbristol still any interest in doing that? Else I would consider taking your PR as basis and doing it myself.
>
> Hi, yes thanks for the reply. I'm happy to define a new template and update the docs.

While you are doing this, look to see what other properties are not in the 
existing template and let's see if we can include anything significant.

David Lang

2022-04-04 10:11 UTC, rgerhards commented
@artbristol interest in finishing this PR? Else, I'll close it unmerged (doing some cleanup right now). Thx!

2022-04-05 15:25 UTC, artbristol commented
@rgerhards I've moved the changes to the default template into a new template and updated the docs in the linked PR

2022-04-06 07:15 UTC, rgerhards approved these changes

2022-04-06 07:16 UTC, merged