NEW CONTRIB::FFAUP:: URL parser module function using libfaup
rsyslog/rsyslog pull request #4728
Opened 2021-11-05 18:21 UTC by frikilax

## Description
New module function(s) (RainerScript) to parse and extract parts of an URL.

These new functions allow anybody to parse any variable containing URLs, hostnames, DNS queries and such to extract:
- the scheme
- the credentials (if present)
- the tld (with support for second-level TLDs)
- the domain (with and without the tld)
- the subdomain
- the full hostname
- the port (if present)
- the resource path (if present)
- the query string parameters (if present)
- the fragment (if present)

## Requirements
This module relies on the [faup](https://github.com/stricaud/faup) library.
The library should be compiled (see link for instructions on how to compile) and installed on build and runtime machines.

| :exclamation:  Warning   |
|--------------------------|
Even if faup is statically compiled to rsyslog, the library still needs an additional file to work properly: the mozilla.tlds stored by the libfaup library in /usr/local/share/faup. It permits to properly match second-level TLDs and allow URLs such as www.rsyslog.co.uk to be correctly parsed into \<rsyslog:domain\>.\<co.uk:tld\> and not \<rsyslog:subdomain\>.\<co:domain\>.\<uk:tld\>

## HowTo
The module functions are fairly simple to use, and are divided in 2 classes:
- `faup()` allows to parse the entire URL and return all parts in a complete JSON
- `faup_<field>()` allows to parse the entire URL, but only returns the (potential) value of the requested field as string

### Exemples
#### using the `faup()` function
The `faup()` is the simplest function to use, simply provide a value or variable (any type) as the only parameter, and the function returns a json object containing every element of the URL.

*example code:*
```
set $!url = "https://user:pass@www.rsyslog.com:443/doc/v8-stable/rainerscript/functions/mo-faup.html?param=value#faup";

set $.faup = faup($!url);
```

*$.faup will contain:*
```json
{
	"scheme": "https",
	"credential": "user:pass",
	"subdomain": "www",
	"domain": "rsyslog.com",
	"domain_without_tld": "rsyslog",
	"host": "www.rsyslog.com",
	"tld": "com",
	"port": "443",
	"resource_path": "\/doc\/v8-stable\/rainerscript\/functions\/mo-faup.html",
	"query_string": "?param=value",
	"fragment": "#faup"
}
```

| :memo:     Note      |
|---------------------|
This is a classic rsyslog variable, and you can access every sub-key with `$.faup!domain`, `$.faup!resource_path`, etc...

#### using the `faup_<field>()` functions
Using the field functions is even simpler: for each field returned by the `faup()` function, there exists a corresponding function to get only that one field.
For example, if the goal is to recover the domain without the tld, the example above could be modified as follows:
*example code:*
```
set $!url = "https://user:pass@www.rsyslog.com:443/doc/v8-stable/rainerscript/functions/mo-faup.html?param=value#faup";

set $.faup = faup_domain_without_tld($!url);
```

*$.faup will contain:*
```
rsyslog
```

| :memo:     Note      |
|---------------------|
The returned value is no longer a json object, but a simple string

2021-11-05 18:28 UTC, frikilax commented
Note to maintainers : the library used does not have packages for many distributions (I could only find a FreeBSD package), so testing will require compilation of the project.
The library doesn't need anything other than building tools to compile, and is fairly fast to do so, so there shouldn't be any problems on that part.
Feel free to contact me if things needs to be changed/for questions.

2021-11-05 18:30 UTC, frikilax commented
Also : hello @stricaud ! 👋

2021-11-08 11:32 UTC, rgerhards commented
Thx! A first quick comment: I think the module should not be enabled by default.

I will also look into the requirements to run the tests.

2021-11-10 06:39 UTC, stricaud commented
Thanks for the ping @frikilax this looks very cool. Happy to help with anything if I can make the integration smoother.

2021-11-11 09:54 UTC, rgerhards requested changes
I don't see exactly what is wrong, but the faup module is obviously also compiled if not selected. Even if selected, and libfaup is present, compilation fails (probably due to invalid USE_FAUP definition).

2021-11-11 09:54 UTC, rgerhards commented on configure.ac
> +
looks duplicated ;-)

2021-11-11 09:54 UTC, rgerhards commented
Ubuntu 20 CI system now has libfaup.

2021-11-11 10:56 UTC, rgerhards commented
I fixed part of the configure.ac issue, but maintainer pushes to the repro are not permitted.  For starters, in line 413 of configure.ac you need to change to `[enable_ffaup=no]`.

2021-11-15 11:57 UTC, rgerhards commented
@frikilax Please have a look at the Ubuntu 20 and Fedora 34 CI failures. There are compile issues, at quick look it looks just like a little bit cleanup needs to be done on the code. Ubuntu 20 and F 34 are currently the only environments where libfaup is present. I'll enable others most probably when CI passes on these environments (maybe early, depending on workload).

2021-11-19 08:56 UTC, frikilax commented on configure.ac
> +
Solved !

2021-11-19 09:20 UTC, rgerhards commented
@frikilax The Fedora 34 fail looks like something is not really clean in regard to the tests (or some other platform foo...)

2021-11-19 10:16 UTC, rgerhards commented
@frikilax hold on, this may be a problem inside the container - looking at it

2021-11-19 11:37 UTC, rgerhards approved these changes

2021-11-22 08:03 UTC, merged