conf: Fix #pragma GCC diagnostic not allowed inside functions
rsyslog/rsyslog pull request #4957
Opened 2022-08-10 16:08 UTC by julthomas

Commit 829a6f6 "CI: improve use of github action matrix feature;
optimization" has introduced use of #pragma GCC diagnostic in function
doNameLine() of runtime/conf.c. This is not supported by old compilers
like GCC 4.4.7 on el6.

2022-08-17 11:02 UTC, rgerhards requested changes
sry for the late reply and thx for the PR.

Unfortunately, you hit the wrong spot. The right location to fix is here: https://github.com/rsyslog/rsyslog/blob/master/runtime/rsyslog.h#L94

2022-08-18 22:28 UTC, julthomas commented
Hello @rgerhards, I rebased, is it OK?

2022-08-19 06:43 UTC, rgerhards approved these changes

2022-08-19 06:43 UTC, rgerhards commented
> Hello @rgerhards, I rebased, is it OK?

looks perfect, thx!

2022-08-19 06:44 UTC, merged