WiP: New fac-sever-rewrite.py for Python 3
rsyslog/rsyslog pull request #5271
Opened 2023-11-08 17:58 UTC by OrangeDog

Rewrite the plugin for Python 3, adding CLI arguments to make it useful out of the box.

I've not fully tested this yet, but I'm about to start using it myself.

Are you interested in taking this, and if so is anything else required?

2023-11-09 12:02 UTC, rgerhards requested changes
small license nit. Not to offend, but do it right.

2023-11-09 12:02 UTC, rgerhards commented on plugins/external/messagemod/fac-sever-rewrite/fac-sever-rewrite.py
> +Copyright (c) 2023 James Howe
it's a bit picky, but you need to retain the old copyright, because this is derived work. Of course, add your own in addition.

2023-11-09 12:11 UTC, OrangeDog commented on plugins/external/messagemod/fac-sever-rewrite/fac-sever-rewrite.py
> +Copyright (c) 2023 James Howe
I guess I did technically copy some of the comments. How should I format this?

```
Copyright (C) 2014 by Adiscon GmbH
Copyright (c) 2023 James Howe
```
or
```
Copyright (c) 2014-2023 by Adiscon GmbH and James Howe
```
or something else?

2023-11-09 14:55 UTC, rgerhards commented on plugins/external/messagemod/fac-sever-rewrite/fac-sever-rewrite.py
> +Copyright (c) 2023 James Howe
Both ways are fine. Even comments can be under copyright, and I always prefer to play it safe ;-) Thx for your attention.

2023-11-09 15:06 UTC, OrangeDog commented
I assume the test failure has nothing to do with this change?

2023-11-09 15:09 UTC, rgerhards commented
Well, it complains that the commits are not squashed. We prefer to have a clean history, so a single commit will do here. I can squash later on if you don't like to do that.

The other runs may have some flakes, I'll look into that if it happens.

2023-11-09 15:33 UTC, OrangeDog commented
> The other runs may have some flakes, I'll look into that if it happens.

That is what I was referring to, before the latest commit tripped the other issue.

2023-11-10 08:21 UTC, rgerhards commented
@OrangeDog just FYI: it looks like we have issues with a set of CI builders. This is causing the failures. I am investigating the problem.

2023-12-08 17:10 UTC, rgerhards approved these changes

2023-12-08 17:58 UTC, OrangeDog commented
I see clicking the "update branch" button in GitHub to get it to rebuild also violates the PR structure validation.
I can fix that next week if necessary.

2023-12-11 08:21 UTC, rgerhards commented
@OrangeDog Please have a look at https://github.com/rsyslog/rsyslog/pull/5291 -- if it is OK from you PoV, I can push it to your branch and so merge the original PR.

2023-12-11 09:05 UTC, OrangeDog commented
Not sure what was ruined about it, but I already did the rebase here.

2023-12-11 09:09 UTC, rgerhards commented
This looks great now! Thanks.

2023-12-11 12:42 UTC, OrangeDog commented
Test failure appears to be because elasticsearch didn't start?

2024-01-10 09:43 UTC, OrangeDog commented
@rgerhards I'd love to see this merged, but I don't think I can do anything about the test issues. They appear to be unrelated?

2024-01-10 11:00 UTC, rgerhards commented
Yeah, I'll take care of it. Have been busy over the holidays and am currently deeply involved in setting up the new doc work: https://www.rsyslog.com/improving-the-rsyslog-documentation/

As this is a non-critical PR and the next scheduled stable was far away, I did not focus here. Sry for not explaining!

2024-01-10 11:50 UTC, merged